
spring: 
  config.activate.on-profile: default
  datasource:
    url: jdbc:h2:mem:testdb
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        discriminator:
            ignore_explicit_for_joined: false
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      # springframework.orm.jpa: DEBUG
      # springframework.transaction: DEBUG
      # springframework.transaction.interceptor: trace
      hibernate:
        type:
          descriptor:
            sql: trace




---
spring:
  config.activate.on-profile: nosql
  datasource:
    url: jdbc:h2:mem:testdb
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        discriminator:
            ignore_explicit_for_joined: false
        # show_sql: true
        format_sql: true
